### ISSUE TITLE
Ambiguous abbreviation rules in syntax

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/stata-linter#11]
https://github.com/mizuhirosuzuki/stata-linter/blob/06525640f76245b605223bf619c93fb82d35b218/src/stata_linter_detect.ado#L17

https://github.com/mizuhirosuzuki/stata-linter/blob/06525640f76245b605223bf619c93fb82d35b218/src/stata_linter_detect_all.ado#L10

https://github.com/mizuhirosuzuki/stata-linter/blob/06525640f76245b605223bf619c93fb82d35b218/src/stata_linter_correct.ado#L14

In Stata capitalization of options means something specific. Capitalization indicates shortest allowed abbreviation. So `Input(string)` in the syntax definition means that when using the command you may write `input()`, `inpu()`, `inp()` all the way down to the capitalized letter, as in `i()`. 

So in the example above you have both `Input(string)` and `Indent(string)`. I do not know what actual happens here, but it is ambiguous and we do not want that. Perhaps we can do `INPut(string)` and `INDent(string)`

**Comment by mizuhirosuzuki** [comment]
Thanks Kris, I fixed that.

**Comment by kbjarkefur** [comment]
Thank Hiro! Maybe it is just me, but I can't find the commit that fixed it.

**Comment by mizuhirosuzuki** [comment]
I ddin't push the fixed codes yet. (As the best github practice, should I close the issue after I push or merge the fixes?)

**Comment by kbjarkefur** [comment]
In `ietoolkit` and `iefieldkit` we only close once it is published on ssc, as the issue for the user has not gone away until then. 

But as a minimum when there is no publication, then it should not be closed until it is pushed.

When you close it link to the commit where it was fixed so the connection to issue and solution is well documented.

And finally, do not keep too much code unpushed on your computer. If you still want to review it, push it to a branch that you only merge when reviewed. Otherwise we miss out on the collaborative aspect of GitHub if we cannot see what the rest of your team is currently working on, and your code is not back-uped properly until it is on the origin repo.

**Comment by mizuhirosuzuki** [comment]
Great, thanks Kris, I'm learning a lot! I will push my commits and add the link to the commit.
