### ISSUE TITLE
Correct file paths from \ to /

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/stata-linter#13]
The Stata command should accept both `\` and `/` but the command should replace `\` with `/` before passing it to the python function as python will interpret paths with `\` incorrectly.

This will make it much more user friendly to Stata users

**Comment by mizuhirosuzuki** [comment]
I was thinking to include this but this is a bit tricky since `\` is used in matrix expressions in Stata. For now I don't have a good idea of how to distinguish backslahes in file paths from backslashes in matrix expressions. I'll think a bit more about how I can do this.

**Comment by kbjarkefur** [comment]
I wasn't clear. This only for file paths passed as option in `input()`.

It will only matter in the file path you pass in `input` here: 

https://github.com/mizuhirosuzuki/stata-linter/blob/06525640f76245b605223bf619c93fb82d35b218/src/stata_linter_detect.ado#L44

So it only matters in paths python will try open or in any other way handle. It will not matter in the part the parses through do-files as the python script does not use them to open or handle files.

**Comment by mizuhirosuzuki** [comment]
oh ok, I misunderstood your point. I see, it should be easy to fix.

**Comment by kbjarkefur** [comment]
yes, and it would never be an issue on Mac or Linux, but most Stata users are PC users

**Comment by RRMaximiliano** [comment]
Closed in #20
