### ISSUE TITLE
Run directly from Python

### ISSUE THREAD

**Issue by jeff-m-sullivan** [worldbank/stata-linter#22]
I'd like the ability to run directly from Python so that we can run the linter in GitHub Actions and other CI systems that won't have Stata installed.

I'm already working on implementing this feature and will submit a PR once it is ready.

In the meantime, you can check it out here if interested: https://github.com/jeff-m-sullivan/stata-linter/tree/run-direct

**Comment by kbjarkefur** [comment]
This is awesome! Thanks for working on a contribution. Something like this has been in our medium term plans, but we have not started to work on this.

Our plan has been to first focus on the rules and checks that the linter use make sense to more people than just our immediate team. As long as your implementation can handle that rules are being updated, then this contribution is brilliant! Thanks!

**Comment by jeff-m-sullivan** [comment]
Glad to hear it. Yes, it can indeed handle changing rules. I just wrapped stata_linter_detect_py in a command-line parsing function and added an entry point for it. The PR is open now. Looking forward to feedback.

**Comment by RRMaximiliano** [comment]
Awesome, Thanks for this @jeff-m-sullivan. As Kris mentioned, we were planning to have this in our mid-term. We have some minor changes to the output before we release it and then I will take a look at your PR.
