### ISSUE TITLE
Remove `nocheck` option

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/stata-linter#24]
Remove the option `nocheck`. It's described as follows in the current (v0.04) version:

>     nocheck                    Do not show suggestions to check and only show style problems

**Comment by luisesanmartin** [comment]
Note that this should also be removed in the help file

**Comment by luizaandrade** [comment]
#26 is still not working for me, and I believe the issue is still related to #30

**Comment by luizaandrade** [comment]
resolved by #26

**Comment by luisesanmartin** [comment]
@luizaandrade can we close this issue now or should we wait until #32 is merged into `main`?
