### ISSUE TITLE
Fix function _getfilepath

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/stata-linter#29]
This function is only looking at the string, and not checking whether the folder path actually exists. So if someone simply write the name of a do-file without the file format .do, it will not understand that it's meant to be a do-file.

**Comment by luizaandrade** [comment]
- [ ] Switch all slashes to forward slashes
- [ ] Check if input contains any dots
  - [ ] If it does, extract the last one and consider it the file format
    - [ ] Test that the file format is .do
      - [ ] If it is, that's it
      - [ ] If it is not, return an error
  - [ ] If it does not, test if it is a folder (that is, check that a folder with that name exists)
    - [ ] If it is, consider that's it
    - [ ] If it is not, test that a do file with that name  + . do exists
      - [ ] If it does, return the name with .do in the end
      - [ ] If it does not, return an error

**Comment by mizuhirosuzuki** [comment]
Just a quick comment, for the second point, instead of finding any dots, python's os package has "os.path.basename" function to return the file name (I guess if it's a folder, it returns nothing). Or, more directly, you may be able to use "os.path.splitext" to get the file extension and see if it's a do file or not.

**Comment by luizaandrade** [comment]
Thanks, Hiro! This is great, but this part of the code is implemented in Stata, which unfortunately does not have this functionality automated...

**Comment by mizuhirosuzuki** [comment]
oh no! sorry then never mind
