### ISSUE TITLE
Check that versions of Python scripts and the ado file are the same

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/stata-linter#30]
I see @RRMaximiliano has made a lot of updates on the Python code. However, when I run the run file, I still see the old version of outputs -- I assume this is because I have the earlier version installed. What do I need to do to use the updated Python functions?

**Comment by luizaandrade** [comment]
1. remove current Stata linter installing
2. add github folder to top of adopath
3. restart Stata

**Comment by luisesanmartin** [comment]
maybe there's a way to update `.py` files too everytime we run `net install ...` to try code from a development branch?

**Comment by luizaandrade** [comment]
Hardcode linter version in both `ado` and `py` and check that they are the same before running. Throw an error if it's not.

**Comment by luizaandrade** [comment]
The easiest fix is to simply remove the `.pkg` file from this repo, and only support SSC installation

**Comment by luisesanmartin** [comment]
I'm changing the name of this issue so it's more accurate with what we're correcting.
Regarding the test of updated Python code, updated Python scripts will be loaded by Stata after updating the package with `net install ...` or `ssc install ...` and restarting the Stata session
