### ISSUE TITLE
Edit installation instructions

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/stata-linter#36]
- [x] Install from SSC
- [x] Python needs to be installed and accessible to Stata
- [x] pandas needs to be installed

**Comment by luisesanmartin** [comment]
instalation from SSC is pending to be added in the README. It will be added once we receive confirmation that the command is posted there

**Comment by luisesanmartin** [comment]
command is available in ssc and the instructions were updated in the README. Closing the issue now
