### ISSUE TITLE
Breaking lines with 80+ chars not working in all cases

### ISSUE THREAD

**Issue by luisesanmartin** [worldbank/stata-linter#53]
This piece of code:
```{stata}
		iebaltab weight price   , grpvar(tmt)      pairoutput("p") ftestoutput("p")  replace savecsv("${ietoolkit}/run/output/iebaltab/iebt_csv")  savexlsx("${ietoolkit}/run/output/iebaltab/iebt_xlsx") ///
    browse  onerow  ftest feqtest  ///
     starlevels(.35 .222 .05)   grpcodes fix(rep78)  covar(mpg) ///
      totallabel("TOOOT") ///
    rowlabels("price Price in dollar @ weight vikt")  tblnonote
```
is corrected to:
```{stata}
    iebaltab weight price   , grpvar(tmt)      pairoutput("p") ftestoutput("p")  replace savecsv("${ietoolkit}/run/output/iebaltab/iebt_csv")  savexlsx("${ietoolkit}/run/output/iebaltab/iebt_xlsx") ///
    browse  onerow  ftest feqtest  ///
     starlevels(.35 .222 .05)   grpcodes fix(rep78)  covar(mpg) ///
      totallabel("TOOOT") ///
    rowlabels("price Price in dollar @ weight vikt")  tblnonote
```
which still contains a line with more than 80 chars. The correction feature for long lines doesn't work in this case

**Comment by kbjarkefur** [comment]
I think it is the same issue as described in #55 and in #55 I think it is more succinctly expressed. But maybe still keep this open and test if this is still is the case when #55 is solved

**Comment by luisesanmartin** [comment]
> I think it is the same issue as described in #55 and in #55 I think it is more succinctly expressed. But maybe still keep this open and test if this is still is the case when #55 is solved

I'm checking this issue now. Can it be that you actually meant #54?
