### ISSUE TITLE
{} in comment creates error

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/stata-linter#57]
`{}` in a comment, for example `* Missing space before {}`, results in this error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\ado\plus\py\stata_linter_correct.py", line 177, in indent_in_bracket
    bracket_pair.append([loop_start.pop(), line_index, nest_level, bracket_start.pop()])
IndexError: pop from empty list
r(7102);```

**Comment by luisesanmartin** [comment]
I'm trying to replicate this error but it's not showing for me. When I try `lint dofile.do` in a dofile with this content
```{stata}
* Missing space before {}
set obs 10
gen var = _n
```
the expected output is returned
![image](https://user-images.githubusercontent.com/38444484/179539603-e3aeb6de-d10b-4af2-ba42-63e501d19336.png)

I'm using the branch `develop-v0-bugs` as of July 18 2022. One possibility is that some of the errors I already worked on in this branch nd previously in `develop` addressed this problem.

@kbjarkefur when you have some time, please try to replicate this issue again and let me know how it goes. Thanks.
