### ISSUE TITLE
indent_in_bracket crashes in some instances

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/stata-linter#7]
`indent_in_bracket()` crashes in some do-files but not all. I have not been able to figure out what code causes this so I'm not able to reproduce this minimally yet, maybe it is possible to detect the issue from the error.

[analysis.txt](https://github.com/mizuhirosuzuki/stata-linter/files/5704146/analysis.txt) (need to rename to .do, GitHub won't accept that extension on upload)

```
= python: indent_in_bracket("/Users/bbdaniels/GitHub/mumbai-public/do/analysis_corr
> .do", "/Users/bbdaniels/GitHub/mumbai-public/do/analysis_corr.do", "2", "2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 44, in indent_in_bracket
IndexError: pop from empty list
```

**Comment by mizuhirosuzuki** [comment]
I think the problem is "forv" is used for "forvalues" in the file. I will fix it.

**Comment by bbdaniels** [comment]
yeah, stata abbreviations are lovely, you have to cover everything in between the shortest abbrev and the full command: https://github.com/kylebarron/language-stata/blob/625e43d5d2d0713f07238d350afde8096ffb8140/grammars/stata.cson#L617

<img width="582" alt="Screen Shot(176)" src="https://user-images.githubusercontent.com/1459122/102382419-724a8f80-3f98-11eb-8146-81e7d6439a28.png">
