### ISSUE TITLE
Whitespace rules not applied correctly for negative numbers

### ISSUE THREAD

**Issue by razvanazamfirei** [worldbank/stata-linter#71]
Add whitespaces around math symbols (`+`, `=`, `<`, `>`):

Command flags cases when a negative sign precedes a number, even if whitespace rules are otherwise respected.
`x = -5.5`
The number will still evaluate correctly in most situations if a space is added after the negative sign, but it's not standard syntax and can fail.
This can be verified if you run:
`egen var = anymatch(var2 var3 var4), v(- 3)` 
which will throw a 121 - invalid numlist error. 

---
This is not an issue per se, just a stylistic comment, but when defining syntax the preferred format is 
`syntax varlist(min=2 max=4 numeric)` as opposed to `syntax varlist(min = 2 max = 4 numeric)`.

**Comment by luisesanmartin** [comment]
Hi @razvanazamfirei. This is noted. We'll work on it in the next release of a subversion

**Comment by luisesanmartin** [comment]
corrected in v1.02
