### ISSUE TITLE
repec abstract - link to repo is incorrect

### ISSUE THREAD

**Issue by rpguiteras** [worldbank/stata-linter#76]
https://ideas.repec.org/c/boc/bocode/s459150.html

"For more info about this linter, see https://github.com/worldbank/stata_linter"

should be

"For more info about this linter, see https://github.com/worldbank/stata-linter"

**Comment by luisesanmartin** [comment]
@rpguiteras thanks for flagging this. We'll update the description in the next version of the command by next week

**Comment by luisesanmartin** [comment]
corrected in v1.02
